name: API CI

#on:[push]
on:
  push:
    paths:
      - "./api/**"
      - ".github/workflows/api-ci.yml"

defaults:
  run:
    working-directory: ./api

#vamos a correr el codigo en un contenedor en la nube!
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: ./api/package-lock.json
      - name: Install dependencies
        shell: bash
        run: npm ci
      - name: Run unit tests
        shell: bash
        run: npm run test

  static-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: ./api/package-lock.json
      - name: Install dependencies
        shell: bash
        run: npm ci
      - name: Run unit tests
        shell: bash
        run: npm run lint

  e2e-test:
    runs-on: ubuntu-latest
    container:
      image: node:22

    services:
      mongo-e2e:
        image: mongo:latest
        ports:
          - 27021:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root123

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        shell: bash
        run: npm ci
      - name: Run e2e tests
        shell: bash
        run: npm run test:e2e
        env:
          MONGO_DB_NAME: demo
          MONGO_URL: mongodb://test:test123@mongo-e2e:27021?retryWrites=true&writeConcern=majority

